import { Place } from "@/lib/places/types";

export const krakowPlaces: Place[] = [
  {
    id: "krk-1",
    name: "Stary Kleparz Market",
    categories: ["food", "shopping"],
    description: "Historic open-air market with local produce, flowers, and street food stalls.",
    rating: 4.5,
    priceLevel: 1,
    city: "Krakow",
    distanceFromCenterKm: 0.8,
    openNow: true,
    tags: ["local", "casual"],
  },
  {
    id: "krk-2",
    name: "Wawel Royal Castle",
    categories: ["culture", "outdoors"],
    description: "Iconic hilltop castle complex overlooking the Vistula River.",
    rating: 4.8,
    priceLevel: 2,
    city: "Krakow",
    distanceFromCenterKm: 1.2,
    openNow: true,
    tags: ["historic", "landmark"],
  },
  {
    id: "krk-3",
    name: "Kazimierz Food Tour Stop: Plac Nowy",
    categories: ["food", "nightlife"],
    description: "Buzzing square known for zapiekanka stalls and late-night bars.",
    rating: 4.3,
    priceLevel: 1,
    city: "Krakow",
    distanceFromCenterKm: 2.0,
    openNow: true,
    tags: ["street food", "lively"],
  },
  {
    id: "krk-4",
    name: "Bunkier Sztuki Gallery",
    categories: ["culture"],
    description: "Contemporary art gallery with rotating exhibitions in the city center.",
    rating: 4.2,
    priceLevel: 1,
    city: "Krakow",
    distanceFromCenterKm: 0.5,
    openNow: false,
    tags: ["art", "indoor"],
  },
  {
    id: "krk-5",
    name: "Jordan Park",
    categories: ["outdoors", "wellness"],
    description: "Large green park with walking paths, a pond, and sports fields.",
    rating: 4.6,
    priceLevel: 0,
    city: "Krakow",
    distanceFromCenterKm: 3.5,
    openNow: true,
    tags: ["relaxing", "family-friendly"],
  },
  {
    id: "krk-6",
    name: "Forum Przestrzenie",
    categories: ["nightlife", "food"],
    description: "Riverside bar and event space in a former hotel, popular in summer.",
    rating: 4.4,
    priceLevel: 2,
    city: "Krakow",
    distanceFromCenterKm: 1.8,
    openNow: true,
    tags: ["riverside", "trendy"],
  },
  {
    id: "krk-7",
    name: "Cloth Hall Boutiques",
    categories: ["shopping", "culture"],
    description: "Renaissance-era hall in the Main Square filled with craft and souvenir stalls.",
    rating: 4.1,
    priceLevel: 2,
    city: "Krakow",
    distanceFromCenterKm: 0.2,
    openNow: true,
    tags: ["souvenirs", "historic"],
  },
  {
    id: "krk-8",
    name: "Hala Stulecia Spa & Wellness",
    categories: ["wellness"],
    description: "Modern spa offering massages, saunas, and thermal pools.",
    rating: 4.7,
    priceLevel: 3,
    city: "Krakow",
    distanceFromCenterKm: 4.2,
    openNow: false,
    tags: ["relaxing", "premium"],
  },
  {
    id: "krk-9",
    name: "Kolanko No.6",
    categories: ["nightlife", "food"],
    description: "Cozy pub with board games, craft beer, and a laid-back crowd.",
    rating: 4.5,
    priceLevel: 1,
    city: "Krakow",
    distanceFromCenterKm: 2.3,
    openNow: true,
    tags: ["cozy", "casual"],
  },
  {
    id: "krk-10",
    name: "Kosciuszko Mound Trail",
    categories: ["outdoors"],
    description: "Walking trail up a historic earthen mound with panoramic city views.",
    rating: 4.4,
    priceLevel: 1,
    city: "Krakow",
    distanceFromCenterKm: 5.0,
    openNow: true,
    tags: ["hike", "views"],
  },
  {
    id: "krk-11",
    name: "Massolit Books & Cafe",
    categories: ["culture", "food"],
    description: "English-language bookstore with a cafe tucked in the back rooms.",
    rating: 4.6,
    priceLevel: 1,
    city: "Krakow",
    distanceFromCenterKm: 1.5,
    openNow: true,
    tags: ["quiet", "books"],
  },
  {
    id: "krk-12",
    name: "Szara Gęś Fine Dining",
    categories: ["food"],
    description: "Upscale Polish fine-dining restaurant on the Main Square.",
    rating: 4.7,
    priceLevel: 3,
    city: "Krakow",
    distanceFromCenterKm: 0.3,
    openNow: true,
    tags: ["fine dining", "romantic"],
  },
  {
    id: "krk-13",
    name: "Cricoteka Theatre Museum",
    categories: ["culture"],
    description: "Museum dedicated to avant-garde theatre director Tadeusz Kantor.",
    rating: 4.0,
    priceLevel: 1,
    city: "Krakow",
    distanceFromCenterKm: 2.7,
    openNow: false,
    tags: ["museum", "indoor"],
  },
  {
    id: "krk-14",
    name: "Prozak 2.0 Nightclub",
    categories: ["nightlife"],
    description: "Multi-level nightclub with resident DJs, open late on weekends.",
    rating: 4.0,
    priceLevel: 2,
    city: "Krakow",
    distanceFromCenterKm: 0.6,
    openNow: true,
    tags: ["dancing", "late-night"],
  },
  {
    id: "krk-15",
    name: "Galeria Krakowska",
    categories: ["shopping"],
    description: "Large shopping mall next to the main train station.",
    rating: 4.3,
    priceLevel: 2,
    city: "Krakow",
    distanceFromCenterKm: 0.9,
    openNow: true,
    tags: ["mall", "indoor"],
  },
  {
    id: "krk-16",
    name: "Yoga Flow Studio Kazimierz",
    categories: ["wellness"],
    description: "Drop-in yoga studio offering morning and evening classes.",
    rating: 4.8,
    priceLevel: 1,
    city: "Krakow",
    distanceFromCenterKm: 1.9,
    openNow: true,
    tags: ["yoga", "morning"],
  },
];
