import { Place } from "@/lib/places/types";

export const warsawPlaces: Place[] = [
  {
    id: "waw-1",
    name: "Łazienki Royal Park",
    categories: ["outdoors", "culture"],
    description: "Sprawling palace park with peacocks, lakes, and free summer concerts.",
    rating: 4.8,
    priceLevel: 0,
    city: "Warsaw",
    distanceFromCenterKm: 2.5,
    openNow: true,
    tags: ["park", "landmark"],
  },
  {
    id: "waw-2",
    name: "POLIN Museum",
    categories: ["culture"],
    description: "Museum of the History of Polish Jews with award-winning exhibitions.",
    rating: 4.7,
    priceLevel: 2,
    city: "Warsaw",
    distanceFromCenterKm: 1.1,
    openNow: false,
    tags: ["museum", "indoor"],
  },
  {
    id: "waw-3",
    name: "Hala Koszyki Food Hall",
    categories: ["food"],
    description: "Restored industrial market hall packed with food stalls and bars.",
    rating: 4.5,
    priceLevel: 2,
    city: "Warsaw",
    distanceFromCenterKm: 1.6,
    openNow: true,
    tags: ["food hall", "trendy"],
  },
  {
    id: "waw-4",
    name: "Vistula Boulevards",
    categories: ["outdoors", "nightlife"],
    description: "Riverside promenade with bars, food trucks, and beach volleyball courts in summer.",
    rating: 4.4,
    priceLevel: 1,
    city: "Warsaw",
    distanceFromCenterKm: 1.9,
    openNow: true,
    tags: ["riverside", "summer"],
  },
  {
    id: "waw-5",
    name: "Warsaw Uprising Museum",
    categories: ["culture"],
    description: "Immersive museum documenting the 1944 Warsaw Uprising.",
    rating: 4.8,
    priceLevel: 1,
    city: "Warsaw",
    distanceFromCenterKm: 2.8,
    openNow: true,
    tags: ["museum", "historic"],
  },
  {
    id: "waw-6",
    name: "Plac Zbawiciela Cafes",
    categories: ["food", "nightlife"],
    description: "Trendy square ringed by cafes and cocktail bars, popular at night.",
    rating: 4.3,
    priceLevel: 2,
    city: "Warsaw",
    distanceFromCenterKm: 2.2,
    openNow: true,
    tags: ["cafes", "lively"],
  },
  {
    id: "waw-7",
    name: "Złote Tarasy Mall",
    categories: ["shopping"],
    description: "Glass-domed shopping center right next to Warsaw Central Station.",
    rating: 4.2,
    priceLevel: 2,
    city: "Warsaw",
    distanceFromCenterKm: 0.4,
    openNow: true,
    tags: ["mall", "central"],
  },
  {
    id: "waw-8",
    name: "Dolina Szwajcarska Wellness Garden",
    categories: ["wellness", "outdoors"],
    description: "Quiet historic garden good for a peaceful walk or picnic.",
    rating: 4.5,
    priceLevel: 0,
    city: "Warsaw",
    distanceFromCenterKm: 2.0,
    openNow: true,
    tags: ["quiet", "garden"],
  },
  {
    id: "waw-9",
    name: "Level 27 Rooftop Bar",
    categories: ["nightlife"],
    description: "Rooftop bar with panoramic skyline views and cocktails.",
    rating: 4.6,
    priceLevel: 3,
    city: "Warsaw",
    distanceFromCenterKm: 3.0,
    openNow: true,
    tags: ["rooftop", "views"],
  },
  {
    id: "waw-10",
    name: "Praga District Street Art Walk",
    categories: ["culture", "outdoors"],
    description: "Self-guided walk through Warsaw's gritty, art-covered Praga district.",
    rating: 4.4,
    priceLevel: 0,
    city: "Warsaw",
    distanceFromCenterKm: 3.6,
    openNow: true,
    tags: ["street art", "free"],
  },
  {
    id: "waw-11",
    name: "Signature Kitchen Fine Dining",
    categories: ["food"],
    description: "Michelin-recommended tasting-menu restaurant in the city center.",
    rating: 4.9,
    priceLevel: 3,
    city: "Warsaw",
    distanceFromCenterKm: 0.7,
    openNow: true,
    tags: ["fine dining", "romantic"],
  },
  {
    id: "waw-12",
    name: "Klub Pardon, To Tu",
    categories: ["nightlife"],
    description: "Alternative bar and cultural venue with live music and DJ nights.",
    rating: 4.2,
    priceLevel: 1,
    city: "Warsaw",
    distanceFromCenterKm: 4.0,
    openNow: false,
    tags: ["live music", "alternative"],
  },
  {
    id: "waw-13",
    name: "Copernicus Science Centre",
    categories: ["culture", "outdoors"],
    description: "Hands-on science museum with a riverside park and planetarium.",
    rating: 4.7,
    priceLevel: 2,
    city: "Warsaw",
    distanceFromCenterKm: 3.2,
    openNow: true,
    tags: ["interactive", "family-friendly"],
  },
  {
    id: "waw-14",
    name: "Mokotów Yoga Loft",
    categories: ["wellness"],
    description: "Boutique studio offering yoga, pilates, and meditation sessions.",
    rating: 4.6,
    priceLevel: 1,
    city: "Warsaw",
    distanceFromCenterKm: 5.5,
    openNow: true,
    tags: ["yoga", "meditation"],
  },
  {
    id: "waw-15",
    name: "Hala Mirowska Market",
    categories: ["food", "shopping"],
    description: "Historic market hall selling fresh produce, cheese, and flowers.",
    rating: 4.3,
    priceLevel: 1,
    city: "Warsaw",
    distanceFromCenterKm: 1.3,
    openNow: true,
    tags: ["market", "local"],
  },
  {
    id: "waw-16",
    name: "Warsaw National Stadium Grounds",
    categories: ["outdoors"],
    description: "Riverside area around the national stadium with paths and lookout points.",
    rating: 4.1,
    priceLevel: 0,
    city: "Warsaw",
    distanceFromCenterKm: 4.8,
    openNow: true,
    tags: ["walk", "views"],
  },
];
